---
## 0. Import & Load Data

In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.float_format', '{:.2f}'.format)

In [4]:
# Load semua dataset
# Sesuaikan path dengan lokasi file kamu
df_users_raw = pd.read_csv('tokopedia_users.csv')
df_trans_raw = pd.read_csv('tokopedia_transactions.csv')
df_deliv_raw = pd.read_csv('tokopedia_deliveries.csv')

# Buat copy untuk dikerjakan
df_users = df_users_raw.copy()
df_trans = df_trans_raw.copy()
df_deliv = df_deliv_raw.copy()

print(f'users    : {df_users.shape}')
print(f'transactions : {df_trans.shape}')
print(f'deliveries   : {df_deliv.shape}')

users    : (50000, 5)
transactions : (300000, 6)
deliveries   : (300000, 4)

In [5]:
df_users

        user_id   join_date  gender    location  age
0      USR00001  2022-04-13  Female  Yogyakarta   21
1      USR00002  2023-03-12  Female     Bandung   33
2      USR00003  2022-09-28  Female     Bandung   20
3      USR00004  2022-04-17  Female     Bandung   25
4      USR00005  2022-03-13  Female     Bandung   56
...         ...         ...     ...         ...  ...
49995  USR49996  2022-09-03    Male       Medan   62
49996  USR49997  2022-07-03     NaN    Surabaya   60
49997  USR49998  2023-02-17    Male  Yogyakarta   49
49998  USR49999  2022-09-30    Male    Makassar   54
49999  USR50000  2023-06-29    Male     Jakarta   44

[50000 rows x 5 columns]

In [6]:
df_trans

,order_id,user_id,order_date,payment_method,promo_amount,total_amount
0,ORD000001,USR01057,2023-09-26,GoPay,0,531947
1,ORD000002,USR26336,2022-08-10,ovo,10000,1054104
2,ORD000003,USR25466,2024-05-21,COD,0,1067647
3,ORD000004,USR42303,2024-06-18,ovo,10000,175629
4,ORD000005,USR29370,2024-03-11,ovo,0,1438378
...,...,...,...,...,...,...
299995,ORD299996,USR28800,2024-06-14,GO-PAY,10000,1664986
299996,ORD299997,USR34293,2023-02-09,bca va,0,1879130
299997,ORD299998,USR18612,2023-03-14,gopay,10000,973388
299998,ORD299999,USR07211,2023-04-09,COD,10000,1545572
299999,ORD300000,USR18382,2022-06-18,bca va,0,343210

In [7]:
df_deliv

         order_id    courier_name dispatch_date delivery_date
0       ORD000001  GoTo Logistics    2023-09-26    2023-09-30
1       ORD000002         SiCepat    2022-08-12    2022-08-16
2       ORD000003             JNE    2024-05-23    2024-05-26
3       ORD000004  GoTo Logistics    2024-06-18    2024-06-23
4       ORD000005         SiCepat    2024-03-13    2024-03-14
...           ...             ...           ...           ...
299995  ORD299996  GoTo Logistics    2024-06-14    2024-06-20
299996  ORD299997             JNE    2023-02-10    2023-02-12
299997  ORD299998  GoTo Logistics    2023-03-14    2023-03-19
299998  ORD299999  GoTo Logistics    2023-04-11    2023-04-15
299999  ORD300000  GoTo Logistics    2022-06-20    2022-06-25

[300000 rows x 4 columns]

---
## 2. Data Cleaning

### 2.1 Eksplorasi Awal (Wajib)

Lakukan eksplorasi menyeluruh pada **ketiga tabel** sebelum membersihkan data apapun.

### Shape dan info umum — lakukan untuk ketiga tabel

In [8]:
df_users.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    50000 non-null  str
 1   join_date  50000 non-null  str
 2   gender     45106 non-null  str
 3   location   50000 non-null  str
 4   age        50000 non-null  int64
dtypes: int64(1), str(4)
memory usage: 3.3 MB

In [9]:
df_users.shape[1]
df_users.shape[0]

50000

In [10]:
df_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        300000 non-null  str
 1   user_id         300000 non-null  str
 2   order_date      300000 non-null  str
 3   payment_method  300000 non-null  str
 4   promo_amount    300000 non-null  int64
 5   total_amount    300000 non-null  int64
dtypes: int64(2), str(4)
memory usage: 23.4 MB

In [11]:
df_trans.shape[0]
df_trans.shape[1]

6

In [12]:
df_deliv.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       300000 non-null  str
 1   courier_name   284915 non-null  str
 2   dispatch_date  300000 non-null  str
 3   delivery_date  300000 non-null  str
dtypes: str(4)
memory usage: 19.9 MB

In [13]:
df_deliv.shape[0]
df_deliv.shape[1]

4

### Tipe data seluruh kolom
### DONE

### Missing values: jumlah dan persentase per kolom, per tabel
### Tampilkan hanya kolom yang memiliki missing values
### DONE

### Distribusi kolom-kolom kritis
### total_amount, promo_amount, payment_method, age, courier_name

In [14]:
df_trans.describe()

       promo_amount  total_amount
count     300000.00     300000.00
mean        7473.60   10896439.24
std        12170.89   98873527.87
min            0.00    -150000.00
25%            0.00     526199.75
50%            0.00    1025482.00
75%        10000.00    1523252.00
max        50000.00  999999999.00

In [15]:
df_trans

,order_id,user_id,order_date,payment_method,promo_amount,total_amount
0,ORD000001,USR01057,2023-09-26,GoPay,0,531947
1,ORD000002,USR26336,2022-08-10,ovo,10000,1054104
2,ORD000003,USR25466,2024-05-21,COD,0,1067647
3,ORD000004,USR42303,2024-06-18,ovo,10000,175629
4,ORD000005,USR29370,2024-03-11,ovo,0,1438378
...,...,...,...,...,...,...
299995,ORD299996,USR28800,2024-06-14,GO-PAY,10000,1664986
299996,ORD299997,USR34293,2023-02-09,bca va,0,1879130
299997,ORD299998,USR18612,2023-03-14,gopay,10000,973388
299998,ORD299999,USR07211,2023-04-09,COD,10000,1545572
299999,ORD300000,USR18382,2022-06-18,bca va,0,343210

In [16]:
df_users.describe()

           age
count 50000.00
mean     39.60
std      14.43
min      15.00
25%      27.00
50%      40.00
75%      52.00
max      64.00

In [17]:
df_deliv.describe()

         order_id    courier_name dispatch_date delivery_date
count      300000          284915        300000        300000
unique     300000               4          1188          1188
top     ORD000001  GoTo Logistics    2023-10-02    2023-08-01
freq            1          120082           466           474

In [18]:
table_2 = df_trans.merge(df_users, on="user_id", how="left")

In [20]:
table_3 = table_2.merge(df_deliv, on="order_id", how="left")

In [23]:
table_3.to_excel("table_3.xlsx")