# 🛒 Project Task: Tokopedia E-Commerce Analytics
## Data Cleaning, Feature Engineering & Exploratory Data Analysis

**Module 2 — Python for Data Analysis | Purwadhika Digital Technology School**

---

> ⚠️ **Jangan di-run dulu.** Copy notebook ini terlebih dahulu, baru kerjakan di file copy-an kamu.

---

### Konteks Bisnis
Tokopedia adalah salah satu platform e-commerce terbesar di Indonesia dengan jutaan pengguna aktif dan ratusan ribu transaksi harian. Dataset ini merepresentasikan data operasional nyata: transaksi pengguna, profil user, dan catatan pengiriman — lengkap dengan semua ketidaksempurnaan data yang biasa ditemukan di sistem legacy.

Kamu berperan sebagai Data Analyst di tim analitik Tokopedia yang diminta untuk menganalisis pola transaksi, perilaku pengguna, dan performa logistik guna mendukung transisi strategi dari *growth-driven* ke *profitability-driven*.

**Dataset (3 tabel):**
- `tokopedia_users.csv` — 50.000 baris
- `tokopedia_transactions.csv` — 300.000 baris  
- `tokopedia_deliveries.csv` — 300.000 baris

---

### ⚠️ Catatan Penting
- Task ini **open-ended** — tidak ada satu jawaban yang mutlak benar
- Yang dinilai: **ketepatan keputusan**, **kualitas justifikasi**, dan **kedalaman analisis**
- Setiap keputusan di Data Cleaning & Feature Engineering **wajib disertai penjelasan** di markdown cell
- EDA dikerjakan **tanpa visualisasi** — gunakan pandas aggregation, filtering, sorting, dan merge

---
## 0. Import & Load Data

In [22]:
import pandas as pd
import numpy as np
from datetime import date, datetime

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.float_format', '{:.2f}'.format)

In [23]:
# Load semua dataset
# Sesuaikan path dengan lokasi file kamu
df_users_raw = pd.read_csv('tokopedia_users.csv')
df_trans_raw = pd.read_csv('tokopedia_transactions.csv')
df_deliv_raw = pd.read_csv('tokopedia_deliveries.csv')

# Buat copy untuk dikerjakan
df_users = df_users_raw.copy()
df_trans = df_trans_raw.copy()
df_deliv = df_deliv_raw.copy()

print(f'users    : {df_users.shape}')
print(f'transactions : {df_trans.shape}')
print(f'deliveries   : {df_deliv.shape}')

users    : (50000, 5)
transactions : (300000, 6)
deliveries   : (300000, 4)

---
## 2. Data Cleaning

### 2.1 Eksplorasi Awal (Wajib)

Lakukan eksplorasi menyeluruh pada **ketiga tabel** sebelum membersihkan data apapun.

In [24]:
# Shape dan info umum — lakukan untuk ketiga tabel
df_users.info()
na_values = df_users.isnull().sum()
na_values.apply(lambda x:f"{x} - {x/len(df_users):.2%}")

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    50000 non-null  str
 1   join_date  50000 non-null  str
 2   gender     45106 non-null  str
 3   location   50000 non-null  str
 4   age        50000 non-null  int64
dtypes: int64(1), str(4)
memory usage: 1.9 MB

user_id         0 - 0.00%
join_date       0 - 0.00%
gender       4894 - 9.79%
location        0 - 0.00%
age             0 - 0.00%
dtype: str

In [25]:
df_trans.info()
na_values = df_trans.isnull().sum()
na_values.apply(lambda x:f"{x} - {x/len(df_trans):.2%}")

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        300000 non-null  str
 1   user_id         300000 non-null  str
 2   order_date      300000 non-null  str
 3   payment_method  300000 non-null  str
 4   promo_amount    300000 non-null  int64
 5   total_amount    300000 non-null  int64
dtypes: int64(2), str(4)
memory usage: 13.7 MB

order_id          0 - 0.00%
user_id           0 - 0.00%
order_date        0 - 0.00%
payment_method    0 - 0.00%
promo_amount      0 - 0.00%
total_amount      0 - 0.00%
dtype: str

In [26]:
df_deliv.info()
na_values= df_deliv.isnull().sum()
na_values.apply(lambda x:f"{x} - {x/len(df_deliv):.2%}")

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       300000 non-null  str
 1   courier_name   284915 non-null  str
 2   dispatch_date  300000 non-null  str
 3   delivery_date  300000 non-null  str
dtypes: str(4)
memory usage: 9.2 MB

order_id             0 - 0.00%
courier_name     15085 - 5.03%
dispatch_date        0 - 0.00%
delivery_date        0 - 0.00%
dtype: str

In [27]:
# Tipe data seluruh kolom

#--- done

In [28]:
# Missing values: jumlah dan persentase per kolom, per tabel
# Tampilkan hanya kolom yang memiliki missing values

#--- done

In [29]:
# Distribusi kolom-kolom kritis
# total_amount, promo_amount, payment_method, age, courier_name

In [30]:
display(df_users.describe(),
df_trans.describe(),
df_deliv.describe())

           age
count 50000.00
mean     39.60
std      14.43
min      15.00
25%      27.00
50%      40.00
75%      52.00
max      64.00

       promo_amount  total_amount
count     300000.00     300000.00
mean        7473.60   10896439.24
std        12170.89   98873527.87
min            0.00    -150000.00
25%            0.00     526199.75
50%            0.00    1025482.00
75%        10000.00    1523252.00
max        50000.00  999999999.00

         order_id    courier_name dispatch_date delivery_date
count      300000          284915        300000        300000
unique     300000               4          1188          1188
top     ORD000001  GoTo Logistics    2023-10-02    2023-08-01
freq            1          120082           466           474

In [31]:
df_trans.loc[df_trans["total_amount"]>0, "total_amount"].value_counts()

total_amount
999999999    2968
1038312         5
272100          4
569810          4
1202358         4
             ...
1664986         1
1879130         1
973388          1
1545572         1
343210          1
Name: count, Length: 272888, dtype: int64

In [32]:
df_trans.loc[df_trans["total_amount"]<=0,["order_id","user_id","order_date","payment_method","promo_amount","total_amount"]]

,order_id,user_id,order_date,payment_method,promo_amount,total_amount
146,ORD000147,USR03087,2023-08-22,GoPay,0,-150000
438,ORD000439,USR36168,2023-06-18,BCA Virtual Account,0,-150000
565,ORD000566,USR37484,2023-11-27,GO-PAY,0,-150000
612,ORD000613,USR33803,2022-08-08,bca va,10000,-150000
653,ORD000654,USR09711,2024-08-09,gopay,0,-150000
...,...,...,...,...,...,...
299537,ORD299538,USR24375,2022-12-21,ovo,0,-150000
299719,ORD299720,USR31958,2022-08-26,bca va,0,-150000
299798,ORD299799,USR47142,2023-11-26,OVO,20000,-150000
299865,ORD299866,USR11226,2023-09-16,GoPay,10000,-150000
299885,ORD299886,USR41689,2023-12-04,GO-PAY,20000,-150000

In [33]:
# Cek konsistensi relasi antar tabel
# Apakah semua order_id di deliveries ada di transactions? Dan sebaliknya?
# - OKE
# Apakah semua user_id di transactions ada di users?
# - OKE

In [34]:
table_check_1 = df_trans.merge(df_deliv, on="order_id", how="inner",indicator=False, suffixes=("_trans", "_deliv"))
table_check_1

,order_id,user_id,order_date,payment_method,promo_amount,total_amount,courier_name,dispatch_date,delivery_date
0,ORD000001,USR01057,2023-09-26,GoPay,0,531947,GoTo Logistics,2023-09-26,2023-09-30
1,ORD000002,USR26336,2022-08-10,ovo,10000,1054104,SiCepat,2022-08-12,2022-08-16
2,ORD000003,USR25466,2024-05-21,COD,0,1067647,JNE,2024-05-23,2024-05-26
3,ORD000004,USR42303,2024-06-18,ovo,10000,175629,GoTo Logistics,2024-06-18,2024-06-23
4,ORD000005,USR29370,2024-03-11,ovo,0,1438378,SiCepat,2024-03-13,2024-03-14
...,...,...,...,...,...,...,...,...,...
299995,ORD299996,USR28800,2024-06-14,GO-PAY,10000,1664986,GoTo Logistics,2024-06-14,2024-06-20
299996,ORD299997,USR34293,2023-02-09,bca va,0,1879130,JNE,2023-02-10,2023-02-12
299997,ORD299998,USR18612,2023-03-14,gopay,10000,973388,GoTo Logistics,2023-03-14,2023-03-19
299998,ORD299999,USR07211,2023-04-09,COD,10000,1545572,GoTo Logistics,2023-04-11,2023-04-15
299999,ORD300000,USR18382,2022-06-18,bca va,0,343210,GoTo Logistics,2022-06-20,2022-06-25

In [35]:
table_check_1.loc[table_check_1["courier_name"].isnull(),"payment_method"].value_counts()
# table_check_1.loc[table_check_1["courier_name"].isnull(),"payment_method"].value_counts().sum()

payment_method
gopay                  1782
Mandiri VA             1767
bca va                 1681
ovo                    1676
GoPay                  1657
OVO                    1649
GO-PAY                 1647
COD                    1639
BCA Virtual Account    1587
Name: count, dtype: int64

In [36]:
is_possible = table_check_1["delivery_date"]<table_check_1["dispatch_date"]

table_check_1["is_possible"] = is_possible
table_check_1
table_check_1.groupby("is_possible").count()

,order_id,user_id,order_date,payment_method,promo_amount,total_amount,courier_name,dispatch_date,delivery_date
is_possible,,,,,,,,,
False,291000,291000,291000,291000,291000,291000,276379,291000,291000
True,9000,9000,9000,9000,9000,9000,8536,9000,9000

In [37]:
table_check_1.loc[table_check_1["courier_name"].isnull(),"delivery_date"].value_counts()

delivery_date
2023-09-08    35
2023-04-22    34
2023-05-28    34
2023-03-21    34
2023-04-18    33
              ..
2021-11-30     1
2022-01-27     1
2021-12-28     1
2022-02-23     1
2021-11-11     1
Name: count, Length: 1107, dtype: int64

In [38]:
table_check_2 = df_trans.merge(df_users, on="user_id", how="inner",indicator=False, suffixes=("_trans", "_users"))
table_check_2

,order_id,user_id,order_date,payment_method,promo_amount,total_amount,join_date,gender,location,age
0,ORD000001,USR01057,2023-09-26,GoPay,0,531947,2023-07-08,Female,Jakarta,20
1,ORD000002,USR26336,2022-08-10,ovo,10000,1054104,2022-01-03,Male,Medan,23
2,ORD000003,USR25466,2024-05-21,COD,0,1067647,2023-07-01,Male,Jakarta,46
3,ORD000004,USR42303,2024-06-18,ovo,10000,175629,2023-06-23,Female,Yogyakarta,35
4,ORD000005,USR29370,2024-03-11,ovo,0,1438378,2023-07-31,Female,Yogyakarta,39
...,...,...,...,...,...,...,...,...,...,...
299995,ORD299996,USR28800,2024-06-14,GO-PAY,10000,1664986,2023-08-28,Male,Bandung,50
299996,ORD299997,USR34293,2023-02-09,bca va,0,1879130,2022-07-17,Male,Medan,49
299997,ORD299998,USR18612,2023-03-14,gopay,10000,973388,2022-05-20,Female,Makassar,64
299998,ORD299999,USR07211,2023-04-09,COD,10000,1545572,2022-12-09,Male,Bandung,46
299999,ORD300000,USR18382,2022-06-18,bca va,0,343210,2022-01-03,Female,Makassar,40

In [39]:
table_check_2.describe()

       promo_amount  total_amount       age
count     300000.00     300000.00 300000.00
mean        7473.60   10896439.24     39.63
std        12170.89   98873527.87     14.44
min            0.00    -150000.00     15.00
25%            0.00     526199.75     27.00
50%            0.00    1025482.00     40.00
75%        10000.00    1523252.00     52.00
max        50000.00  999999999.00     64.00

In [40]:
table_check_1.describe()

       promo_amount  total_amount
count     300000.00     300000.00
mean        7473.60   10896439.24
std        12170.89   98873527.87
min            0.00    -150000.00
25%            0.00     526199.75
50%            0.00    1025482.00
75%        10000.00    1523252.00
max        50000.00  999999999.00

**✍️ Ringkasan Temuan Eksplorasi:**

*(Kolom apa yang bermasalah di setiap tabel, seberapa parah, dan prioritas penanganan kamu)*

>

---
### 2.2 Kerangka Identifikasi Missing Values

Sebelum menangani missing values pada kolom manapun, identifikasi dulu **jenis missing value-nya**. Jenis ini menentukan metode penanganan yang valid.

| Jenis | Definisi Singkat | Implikasi Penanganan | Contoh di Dataset Ini |
|---|---|---|---|
| **MCAR** *(Missing Completely At Random)* | Nilai kosong tidak berkaitan dengan kolom lain. Pola missing benar-benar acak. | Relatif aman di-impute (mean/median/modus) atau di-drop tanpa bias signifikan. | `gender` kosong secara acak tanpa pola tertentu. |
| **MAR** *(Missing At Random)* | Nilai kosong berkaitan dengan kolom **lain**, bukan dengan nilai kolom itu sendiri. | Imputation berbasis kolom lain lebih tepat. Drop bisa menyebabkan bias. | `courier_name` kosong mungkin berkaitan dengan tanggal atau metode pembayaran tertentu. |
| **MNAR** *(Missing Not At Random)* | Nilai kosong berkaitan langsung dengan nilai yang seharusnya ada. Ada alasan sistematis. | Imputation apapun berisiko misleading. Perlu keputusan bisnis eksplisit. | `courier_name` kosong karena order dibatalkan sebelum pickup — nilai kosong itu sendiri adalah informasi. |

> 💡 **Cara Menggunakan Kerangka Ini:**
> Untuk setiap kolom bermasalah, tanyakan:
> 1. Apakah pola missing-nya acak, atau ada pola tertentu?
> 2. Apakah nilai kosong berkaitan dengan kolom lain?
> 3. Apakah nilai kosong itu sendiri mengandung informasi bisnis?
>
> Justifikasi reasoning kamu lebih penting dari labelnya.

---
### 2.3 Penanganan Kolom `payment_method`

Kolom ini menyimpan metode pembayaran yang sama dalam format berbeda: `'GoPay'`, `'gopay'`, `'GO-PAY'` — semuanya merujuk pada layanan yang sama. Perlu distandarisasi agar bisa dianalisis.

> 🧠 **Critical Thinking Prompt:**  
> Standarisasi bisa menyederhanakan analisis, tapi apakah selalu tepat?  
> Apakah `'Mandiri VA'` dan `'BCA Virtual Account'` perlu dibedakan atau digabung menjadi `'virtual_account'`?  
> Keputusan kamu harus didasarkan pada **tujuan analisis**, bukan sekadar kebersihan data.

In [41]:
# Lihat semua nilai unik di payment_method
table_check_1["payment_method"].unique()

<StringArray>
[              'GoPay',                 'ovo',                 'COD',
              'bca va',                 'OVO',          'Mandiri VA',
              'GO-PAY',               'gopay', 'BCA Virtual Account']
Length: 9, dtype: str

**✍️ Mapping standarisasi yang kamu buat:**
- Nilai asli → nilai standar:
- Alasan pengelompokan (apakah Mandiri VA dan BCA VA digabung atau dipisah?):

>

In [44]:
# TODO: Standarisasi payment_method
# - apabila provider paymentnya sama, namun penulisannya berbeda maka bisa disatukan, namun apabila provider paymentnya
# berbeda, harus dipisahkan dengan standar penulisan masing-masing. Alasan mandiri VA dan BCA VA harus dipisah adalah
# untuk alasan permintaan promosi/cashback apabila penggunanya banyak

In [ ]:
table_3=table_check_1.copy()
table_3.replace(to_replace=r"[Gg][Oo][\s\-]?[Pp][Aa][Yy]", value="GoPay", regex=True, inplace=True)
table_3.replace(to_replace=r"[Bb][Cc][Aa][\s]([Vv][Aa]|[Vv]irtual [Aa]ccount)", value="BCA VA", regex=True, inplace=True)
table_3.replace(to_replace=r"[Oo][Vv][Oo]", value="OVO", regex=True, inplace=True)
table_3["payment_method"].unique()

<StringArray>
['GoPay', 'OVO', 'COD', 'BCA VA', 'Mandiri VA']
Length: 5, dtype: str

In [43]:
table_3 = table_check_1.copy()
table_3["payment_method"] = table_3["payment_method"].replace(
    to_replace=r"[Gg][Oo][\s\-_]?[Pp][Aa][Yy]", value="GoPay", regex=True
)
table_3["payment_method"] = table_3["payment_method"].replace(
    to_replace=r"[Bb][Cc][Aa][\s\-_]?([Vv][Aa]|[Vv]irtual[\s]?[Aa]ccount)", value="BCA VA", regex=True
)
table_3["payment_method"] = table_3["payment_method"].replace(
    to_replace=r"[Mm][Aa][Nn][Dd][Ii][Rr][Ii][\s\-_]?([Vv][Aa]|[Vv]irtual[\s]?[Aa]ccount)", value="Mandiri VA", regex=True
)
table_3["payment_method"] = table_3["payment_method"].replace(
    to_replace=r"[Oo][Vv][Oo]", value="OVO", regex=True
)
print(table_3["payment_method"].unique())

<StringArray>
['GoPay', 'OVO', 'COD', 'BCA VA', 'Mandiri VA']
Length: 5, dtype: str

---
### 2.4 Penanganan `total_amount`

Kolom `total_amount` memiliki nilai anomali: negatif (~3.032 baris), nol, dan sangat tinggi (hingga Rp 1 miliar).

> 🧠 **Critical Thinking Prompt:**  
> Nilai negatif di e-commerce bisa berarti refund yang dicatat sebagai transaksi terpisah — bukan error.  
> Nilai Rp 1 miliar mungkin legitimate (pembelian bulk oleh reseller).  
> Keputusan drop vs. flag harus konsisten: jika kamu drop outlier untuk analisis rata-rata harga,  
> apakah kamu juga perlu drop untuk analisis total GMV?

In [ ]:
# Investigasi distribusi total_amount
# Berapa jumlah baris negatif, nol, dan sangat tinggi?

In [ ]:
df_trans.describe()

       promo_amount  total_amount
count     300000.00     300000.00
mean        7473.60   10896439.24
std        12170.89   98873527.87
min            0.00    -150000.00
25%            0.00     526199.75
50%            0.00    1025482.00
75%        10000.00    1523252.00
max        50000.00  999999999.00

In [ ]:
def add_category(total_amount):
    if total_amount<0:
        return "negatif"
    elif total_amount == 0:
        return "enol"
    elif total_amount >= 999999999:
        return "sangat tinggi"
    else:
        return "normal"

ttl_amt_cat = table_3["total_amount"].apply(add_category)
table_3["amount_category"] = ttl_amt_cat
table_3

,order_id,user_id,order_date,payment_method,promo_amount,total_amount,courier_name,dispatch_date,delivery_date,is_possible,amount_category
0,ORD000001,USR01057,2023-09-26,GoPay,0,531947,GoTo Logistics,2023-09-26,2023-09-30,False,normal
1,ORD000002,USR26336,2022-08-10,OVO,10000,1054104,SiCepat,2022-08-12,2022-08-16,False,normal
2,ORD000003,USR25466,2024-05-21,COD,0,1067647,JNE,2024-05-23,2024-05-26,False,normal
3,ORD000004,USR42303,2024-06-18,OVO,10000,175629,GoTo Logistics,2024-06-18,2024-06-23,False,normal
4,ORD000005,USR29370,2024-03-11,OVO,0,1438378,SiCepat,2024-03-13,2024-03-14,False,normal
...,...,...,...,...,...,...,...,...,...,...,...
299995,ORD299996,USR28800,2024-06-14,GoPay,10000,1664986,GoTo Logistics,2024-06-14,2024-06-20,False,normal
299996,ORD299997,USR34293,2023-02-09,BCA VA,0,1879130,JNE,2023-02-10,2023-02-12,False,normal
299997,ORD299998,USR18612,2023-03-14,GoPay,10000,973388,GoTo Logistics,2023-03-14,2023-03-19,False,normal
299998,ORD299999,USR07211,2023-04-09,COD,10000,1545572,GoTo Logistics,2023-04-11,2023-04-15,False,normal
299999,ORD300000,USR18382,2022-06-18,BCA VA,0,343210,GoTo Logistics,2022-06-20,2022-06-25,False,normal

In [ ]:
table_3.groupby(["amount_category"])[["total_amount"]].count()

                 total_amount
amount_category
negatif                  3032
normal                 294000
sangat tinggi            2968

In [ ]:
# Analisis lebih dalam: apakah nilai negatif berkorelasi
#  dengan payment_method atau user tertentu?

In [ ]:
table_3[table_3["amount_category"] == "negatif"][
    ["payment_method"]
].value_counts()

payment_method
GoPay             999
OVO               698
BCA VA            661
COD               340
Mandiri VA        334
Name: count, dtype: int64

In [ ]:
table_3["dispatch_date"].value_counts()

dispatch_date
2023-10-02    466
2023-05-27    464
2023-01-10    462
2023-05-28    461
2023-06-15    459
             ...
2021-10-06      1
2024-12-30      1
2021-09-30      1
2021-10-02      1
2021-10-04      1
Name: count, Length: 1188, dtype: int64

In [ ]:
table_3.to_excel("table_3.xlsx")

**✍️ Analisis & Justifikasi:**
- Nilai anomali yang ditemukan dan jumlah baris terdampak:
- Hipotesis untuk setiap jenis anomali (refund? error sistem? fraud?):
- Keputusan penanganan dan threshold yang dipilih:
- Apakah keputusan kamu konsisten untuk semua use-case analisis?

>

In [ ]:
# TODO: Implementasi keputusan penanganan anomali total_amount

---
### 2.5 Penanganan Anomali Tanggal

Dataset ini memiliki dua jenis anomali tanggal yang berbeda sifatnya — tangani secara terpisah.

> 🧠 **Critical Thinking Prompt:**  
> Kedua anomali ini berbeda secara bisnis. Delivery date sebelum dispatch mungkin hanya human error (swap tanggal).  
> Tapi order sebelum join_date lebih serius — bisa mengindikasikan bug sistematis atau fraud.  
> Keputusanmu untuk masing-masing bisa (dan mungkin harus) berbeda.

In [ ]:
# Konversi kolom tanggal ke datetime terlebih dahulu
table_4 = table_check_1.merge(df_users, on="user_id", how="left",indicator=False, suffixes=("_trans+user", "_users"))
table_4.tail()
# Lakukan di semua tabel yang relevan
table_4["join_date"] = pd.to_datetime(table_4["join_date"])
table_4["order_date"] = pd.to_datetime(table_4["order_date"])
table_4["dispatch_date"] = pd.to_datetime(table_4["dispatch_date"])
table_4["delivery_date"] = pd.to_datetime(table_4["delivery_date"])

table_4.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        300000 non-null  str
 1   user_id         300000 non-null  str
 2   order_date      300000 non-null  datetime64[us]
 3   payment_method  300000 non-null  str
 4   promo_amount    300000 non-null  int64
 5   total_amount    300000 non-null  int64
 6   courier_name    284915 non-null  str
 7   dispatch_date   300000 non-null  datetime64[us]
 8   delivery_date   300000 non-null  datetime64[us]
 9   is_possible     300000 non-null  bool
 10  join_date       300000 non-null  datetime64[us]
 11  gender          270522 non-null  str
 12  location        300000 non-null  str
 13  age             300000 non-null  int64
dtypes: bool(1), datetime64[us](4), int64(3), str(6)
memory usage: 30.0 MB

In [ ]:
# Anomali 1: order_date sebelum join_date
# Investigasi: seberapa besar selisih tanggalnya? Distribusi selisih negatif?

In [ ]:
# Anomali 2: delivery_date sebelum dispatch_date
# Investigasi: berapa distribusi selisih negatifnya? Apakah hanya 1 hari atau lebih?

**✍️ Analisis & Justifikasi — Anomali 1 (order sebelum join):**
- Jenis missing/anomali (MCAR / MAR / MNAR) dan alasan:
- Temuan investigasi (distribusi selisih):
- Hipotesis penyebab:
- Keputusan penanganan dan alasan:

> 

**✍️ Analisis & Justifikasi — Anomali 2 (delivery sebelum dispatch):**
- Temuan investigasi:
- Hipotesis penyebab:
- Keputusan penanganan (swap tanggal? drop? flag?) dan alasan:

>

In [ ]:
# TODO: Implementasi penanganan Anomali 1 (order_date vs join_date)

In [ ]:
# TODO: Implementasi penanganan Anomali 2 (delivery_date vs dispatch_date)

---
### 2.6 Penanganan Missing Values pada `courier_name`

Kolom `courier_name` di tabel deliveries memiliki ~15.085 nilai kosong (~5% dari total baris).

In [ ]:
# Investigasi pola missing values pada courier_name
# Apakah berkorelasi dengan tanggal, lokasi user, atau payment method tertentu?

**✍️ Analisis & Justifikasi:**
- **Jenis missing value (MCAR / MAR / MNAR):** dan alasan klasifikasi kamu:
- Temuan investigasi pola missing:
- Hipotesis bisnis mengapa nilai ini kosong:
- Keputusan penanganan (drop, isi 'Unknown', pertahankan NaN) dan alasan:

>

In [ ]:
# TODO: Implementasi penanganan missing values courier_name

---
### 2.7 Penanganan Duplikat & Integritas Data

Dataset hasil sistem legacy berpotensi memiliki beberapa masalah integritas. Identifikasi satu per satu.

| Jenis Masalah | Key yang Dicek | Kemungkinan Penyebab |
|---|---|---|
| Exact duplicate rows | Semua kolom identik | ETL error, double-load |
| Duplikat order_id | `order_id` saja | Transaksi diproses dua kali |
| Order tanpa delivery | `order_id` di trans tapi tidak di deliv | Order dibatalkan / belum sync |
| Delivery tanpa order | `order_id` di deliv tapi tidak di trans | Data corruption / orphan records |
| User tidak terdaftar | `user_id` di trans tapi tidak di users | Akun dihapus / belum terintegrasi |

> 🧠 **Critical Thinking Prompt:**  
> Tidak semua masalah integritas harus di-drop. Order tanpa delivery mungkin adalah order yang dibatalkan —  
> ini bisa jadi insight bisnis (berapa banyak order yang cancel sebelum diproses?), bukan sekadar noise.  
> Keputusan kamu harus konsisten dengan scope analisis.

In [ ]:
# 1. Cek exact duplicates di setiap tabel

In [ ]:
# 2. Cek duplikat order_id

In [ ]:
# 3. Cek order tanpa delivery dan delivery tanpa order

In [ ]:
# 4. Cek user_id di transactions yang tidak ada di users

**✍️ Analisis & Justifikasi:**
- Jenis masalah yang ditemukan dan jumlah baris terdampak:
- Hipotesis untuk setiap jenis masalah:
- Keputusan penanganan per jenis masalah:
- Apakah masalah integritas ini mempengaruhi scope analisis kamu?

>

In [ ]:
# TODO: Implementasi keputusan penanganan masalah integritas data

---
## 3. Feature Engineering

### 3.1 Fitur Wajib

Buat 8 kolom berikut. Sertakan penjelasan singkat business value-nya di setiap fitur.

#### ⚙️ `payment_method_clean`
*(Sudah dibuat di Section 2.3 — pastikan sudah ada di df_trans)*

#### ⚙️ `is_promo_transaction`

In [ ]:
# TODO: Buat is_promo_transaction (boolean: True jika promo_amount > 0)

#### ⚙️ `delivery_days`

> 💡 Perhatikan anomali negatif yang sudah kamu tangani di Section 2.5. Pastikan hasilnya logis.

In [ ]:
# TODO: Buat delivery_days (delivery_date - dispatch_date dalam hari)

#### ⚙️ `is_sla_met`

> 💡 Tentukan threshold SLA kamu sendiri berdasarkan analisis distribusi delivery_days. Justifikasikan.

**✍️ Threshold SLA yang kamu pilih dan alasannya:**

>

In [ ]:
# TODO: Buat is_sla_met (boolean)
# Lihat distribusi delivery_days terlebih dahulu untuk menentukan threshold

#### ⚙️ `user_tenure_days`

> 💡 Tentukan sendiri tanggal referensi yang kamu gunakan dan justifikasikan.

**✍️ Tanggal referensi yang kamu gunakan dan alasannya:**

>

In [ ]:
# TODO: Buat user_tenure_days di df_users

#### ⚙️ `age_group`

> 💡 Threshold default: Gen Z (15-26), Millennial (27-42), Gen X (43-58), Boomer (59+). Sesuaikan jika perlu.

In [ ]:
# TODO: Buat age_group di df_users

#### ⚙️ `is_repeat_buyer`

In [ ]:
# TODO: Buat is_repeat_buyer
# Hitung frekuensi transaksi per user, lalu flag True jika > 1

#### ⚙️ `gmv_per_transaction`
*(Sudah di-handle di Section 2.4 — pastikan total_amount bersih sudah tersedia)*

In [ ]:
# Verifikasi bahwa gmv_per_transaction (total_amount bersih) sudah tersedia
# Ganti nama jika perlu

---
### 3.2 Fitur Pilihan (Minimal 2)

Pilih minimal 2 dari: `promo_dependency_score`, `dispatch_lag_days`, `courier_sla_rate`, `location_avg_delivery`, atau fitur buatan sendiri.

#### ⚙️ Fitur Pilihan 1: [Isi nama fitur]

**✍️ Business value dari fitur ini:**

>

In [ ]:
# TODO: Implementasi Fitur Pilihan 1

#### ⚙️ Fitur Pilihan 2: [Isi nama fitur]

**✍️ Business value dari fitur ini:**

>

In [ ]:
# TODO: Implementasi Fitur Pilihan 2

---
## 4. Exploratory Data Analysis

> **Aturan:** Semua analisis menggunakan pandas — tanpa visualisasi.  
> Gunakan `.groupby()`, `.agg()`, `.value_counts()`, filtering, sorting, dan **merge antar tabel** saat dibutuhkan.  
> Setiap jawaban **wajib disertai insight** di markdown cell yang tersedia.

---
### 4.1 Analisis Transaksi & GMV

**Soal 1:** Berapa total GMV keseluruhan? Berapa rata-rata, median, dan standar deviasi `total_amount` (setelah cleaning)? Apa yang bisa disimpulkan dari perbedaan mean vs median?

In [ ]:
# Soal 1

**✍️ Insight:**

>

**Soal 2:** Berapa distribusi transaksi berdasarkan `payment_method_clean`? Metode apa yang paling dominan dan apa implikasi bisnisnya?

In [ ]:
# Soal 2

**✍️ Insight:**

>

**Soal 3:** Berapa persentase transaksi yang menggunakan promo? Berapa total `promo_amount` yang dikeluarkan? Bandingkan rata-rata `total_amount` antara transaksi berpromo vs tidak berpromo.

In [ ]:
# Soal 3

**✍️ Insight:**

>

**Soal 4:** Breakdown GMV dan jumlah transaksi per bulan (gunakan `order_date`). Apakah ada tren pertumbuhan? Bulan mana yang memiliki GMV tertinggi dan terendah?

In [ ]:
# Soal 4

**✍️ Insight:**

>

---
### 4.2 Analisis Pengguna & Retensi

**Soal 5:** Berapa distribusi `is_repeat_buyer`? Berapa persen user yang hanya bertransaksi sekali (one-time buyer)?

In [ ]:
# Soal 5

**✍️ Insight:**

>

**Soal 6:** Bandingkan rata-rata `total_amount` antara repeat buyer dan one-time buyer. Apa implikasinya terhadap strategi retensi?

In [ ]:
# Soal 6
# Hint: perlu merge df_trans dengan informasi is_repeat_buyer per user

**✍️ Insight:**

>

**Soal 7:** Berapa distribusi transaksi berdasarkan `age_group`? Kelompok usia mana yang paling aktif dan memiliki nilai transaksi rata-rata tertinggi?

In [ ]:
# Soal 7
# Hint: perlu merge df_trans dengan df_users untuk mendapatkan age_group

**✍️ Insight:**

>

**Soal 8:** Apakah ada perbedaan pola transaksi berdasarkan `location` user? Kota mana yang paling berkontribusi terhadap GMV total?

In [ ]:
# Soal 8

**✍️ Insight:**

>

---
### 4.3 Analisis Logistik & SLA

**Soal 9:** Berapa rata-rata `delivery_days` per `courier_name`? Kurir mana yang paling cepat dan paling lambat? Apakah perbedaannya signifikan secara bisnis?

In [ ]:
# Soal 9

**✍️ Insight:**

>

**Soal 10:** Berapa persentase `is_sla_met` per kurir? Kurir mana yang paling sering melewati batas SLA?

In [ ]:
# Soal 10

**✍️ Insight:**

>

**Soal 11:** Apakah ada perbedaan rata-rata `delivery_days` berdasarkan `location` user? Kota mana yang mengalami pengiriman paling lama?

In [ ]:
# Soal 11
# Hint: perlu merge df_deliv, df_trans, dan df_users

**✍️ Insight:**

>

---
### 4.4 Analisis Perilaku Promo *(Implicit — Business Sense Required)*

> Kamu diminta tim Growth untuk mengevaluasi efektivitas program promo Tokopedia.  
> Tim membutuhkan insights untuk memutuskan apakah budget promo saat ini dialokasikan dengan tepat,  
> atau ada pemborosan yang bisa dipangkas.

Pilih minimal **2 angle analisis** yang paling relevan untuk menjawab kebutuhan bisnis tersebut.

#### 📊 Analisis Promo — Angle 1: [Isi judul]

**✍️ Mengapa kamu memilih angle ini untuk evaluasi efektivitas promo?**

>

In [ ]:
# Angle 1

**✍️ Insight & Rekomendasi:**

>

#### 📊 Analisis Promo — Angle 2: [Isi judul]

**✍️ Mengapa kamu memilih angle ini?**

>

In [ ]:
# Angle 2

**✍️ Insight & Rekomendasi:**

>

---
### 4.5 Analisis Anomali & Kualitas Data *(Implicit — Open Ended)*

> Kamu diminta tim Data Engineering untuk membuat **Data Quality Report**.  
> Tujuan: mendokumentasikan semua anomali, menganalisis dampak bisnisnya, dan memberikan rekomendasi  
> perbaikan pipeline data ke depan.

> 🧠 **Critical Thinking Prompt:**  
> Setiap anomali punya cerita bisnis.  
> Apakah anomali tanggal mengindikasikan bug sistem atau fraud?  
> Berapa kerugian finansial estimasi dari transaksi anomali yang kamu temukan?  
> Rekomendasi terbaik adalah yang spesifik dan actionable.

**Ekspektasi minimal:**
- Minimal 3 jenis anomali berbeda yang dikuantifikasi
- Estimasi dampak finansial dari anomali paling signifikan
- Minimal 1 rekomendasi konkret untuk perbaikan pipeline

**✍️ Pendekatan analisis kualitas data yang kamu pilih:**

>

#### 🔍 Anomali 1: [Nama Anomali]

In [ ]:
# Anomali 1

#### 🔍 Anomali 2: [Nama Anomali]

In [ ]:
# Anomali 2

#### 🔍 Anomali 3: [Nama Anomali]

In [ ]:
# Anomali 3

#### 💰 Estimasi Dampak Finansial

In [ ]:
# Kuantifikasi dampak finansial dari anomali yang paling signifikan

**✍️ Rekomendasi untuk Perbaikan Pipeline Data:**

>

---
## 5. Export Clean Dataset

In [ ]:
# Gabungkan ketiga tabel menjadi satu dataframe final
# Gunakan LEFT JOIN dengan df_trans sebagai tabel utama
# Sertakan semua fitur baru yang telah dibuat

# TODO: Implementasi JOIN
# df_final = df_trans.merge(...).merge(...)

# Export
# df_final.to_csv('tokopedia_clean.csv', index=False)
# print(f'Dataset berhasil disimpan: tokopedia_clean.csv')
# print(f'Shape final: {df_final.shape}')
# print(f'Kolom baru yang ditambahkan: {[c for c in df_final.columns if c not in df_trans_raw.columns]}')

---
## 6. Ringkasan & Refleksi

**Keputusan Data Cleaning yang paling challenging dan mengapa:**

> 

**Temuan paling menarik dari EDA:**

> 

**Rekomendasi bisnis utama yang bisa diberikan kepada manajemen Tokopedia berdasarkan analisis kamu:**

>